[package]
name = "nft-minter-meta"
version = "0.0.0"
edition = "2018"
publish = false
authors = [ "Dorin Marian Iancu, dorin.iancu@elrond.com" ]

[dev-dependencies]

[dependencies.nft-minter]
path = ".."

[dependencies.elrond-wasm-debug]
version = "0.32.0"
